.TH "include/balance.h" 3 "Wed Apr 22 2020" "Smart Automated Banking Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/balance.h \- displays the current balance of chequing and savings accounts  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBbalance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
displays the current balance of chequing and savings accounts 


.PP
\fBParameters\fP
.RS 4
\fIno\fP input parameter and the function does not return anything 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Automated Banking Machine from the source code\&.
