.TH "include/currency_transfer.h" 3 "Wed Apr 22 2020" "Smart Automated Banking Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/currency_transfer.h \- The function transfers the amount between chequing and savings account and writes the transfer history to the file\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcurrency_transfer\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The function transfers the amount between chequing and savings account and writes the transfer history to the file\&. 


.PP
\fBParameters\fP
.RS 4
\fIthere\fP is no input parameter and the function does not return anything\&. On successful execution, the history of transfers made will be written to the file and balance of chequing and savings account will be updated 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Automated Banking Machine from the source code\&.
