.TH "include/currency_exchange.h" 3 "Wed Apr 22 2020" "Smart Automated Banking Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/currency_exchange.h \- the function performs the currency conversion between INR/CAD/USD and displays the amount that was converted  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBcurrency_exchange\fP (int cash, char *type)"
.br
.in -1c
.SH "Detailed Description"
.PP 
the function performs the currency conversion between INR/CAD/USD and displays the amount that was converted 


.PP
\fBParameters\fP
.RS 4
\fIcash\fP - The amount that has to be converted 
.br
\fI*type\fP Pointer to type\&. input currency type which is to be converted\&. There is no output parameter\&. 
.RE
.PP
\fBReturns\fP
.RS 4
the function returns 0 when the conversion has been made\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Automated Banking Machine from the source code\&.
