.TH "include/functions.h" 3 "Wed Apr 22 2020" "Smart Automated Banking Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/functions.h \- Simply contains all the headers of the different function\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'deposit\&.h'\fP
.br
\fC#include 'help\&.h'\fP
.br
\fC#include 'pin_init\&.h'\fP
.br
\fC#include 'withdraw\&.h'\fP
.br
\fC#include 'cheque_book_request\&.h'\fP
.br
\fC#include 'pay_bill\&.h'\fP
.br
\fC#include 'pin_change\&.h'\fP
.br
\fC#include 'switch_statement\&.h'\fP
.br
\fC#include 'transaction\&.h'\fP
.br
\fC#include 'transaction_history\&.h'\fP
.br
\fC#include 'personal_loan\&.h'\fP
.br
\fC#include 'balance\&.h'\fP
.br
\fC#include 'currency_exchange\&.h'\fP
.br
\fC#include 'currency_transfer\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Simply contains all the headers of the different function\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Automated Banking Machine from the source code\&.
