.TH "include/global.h" 3 "Wed Apr 22 2020" "Smart Automated Banking Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/global.h \- contains declarations for globals used in the program  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBbalanceInChequing\fP"
.br
.ti -1c
.RI "float \fBbalanceInSaving\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains declarations for globals used in the program 


.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Automated Banking Machine from the source code\&.
