.TH "include/help.h" 3 "Wed Apr 22 2020" "Smart Automated Banking Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/help.h \- places the request for help  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhelp\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
places the request for help 


.PP
\fBParameters\fP
.RS 4
\fIno\fP input parameter and does not return anything 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Automated Banking Machine from the source code\&.
