.TH "include/pin_change.h" 3 "Wed Apr 22 2020" "Smart Automated Banking Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pin_change.h \- First checks whether the existing pin matches with the pin stored in the file and on changing the pin, the new pin is updated to that file\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpin_change\fP (int attempt)"
.br
.in -1c
.SH "Detailed Description"
.PP 
First checks whether the existing pin matches with the pin stored in the file and on changing the pin, the new pin is updated to that file\&. 


.PP
\fBParameters\fP
.RS 4
\fIattempt\fP and the function returns 0 when the pin has been updated successfully 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Automated Banking Machine from the source code\&.
