.TH "include/pin_init.h" 3 "Wed Apr 22 2020" "Smart Automated Banking Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/pin_init.h \- checks whether the pin entered by the user matches with the PIN stored in the file but the user is only allowed three attempts to enter the correct password to get access to the program  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpin_init\fP (int counter)"
.br
.in -1c
.SH "Detailed Description"
.PP 
checks whether the pin entered by the user matches with the PIN stored in the file but the user is only allowed three attempts to enter the correct password to get access to the program 


.PP
\fBParameters\fP
.RS 4
\fIcounter\fP and the function returns zero on successful execution 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Automated Banking Machine from the source code\&.
