.TH "include/switch_statement.h" 3 "Wed Apr 22 2020" "Smart Automated Banking Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/switch_statement.h \- contains the function call for all the transactions and performs the transaction based on input from the user param[in] c - is the user's choice of the transaction return zero  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBswitch_statement\fP (int c)"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains the function call for all the transactions and performs the transaction based on input from the user param[in] c - is the user's choice of the transaction return zero 


.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Automated Banking Machine from the source code\&.
