.TH "include/transaction_history.h" 3 "Wed Apr 22 2020" "Smart Automated Banking Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/transaction_history.h \- this function prints transactions summary of withdrawal, deposit, currency transfer and bill payment\&. That is, it displays the contents of the file that contains all the stated information\&. param[in] there is no input parameter and the function does not return anything  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtransaction_history\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
this function prints transactions summary of withdrawal, deposit, currency transfer and bill payment\&. That is, it displays the contents of the file that contains all the stated information\&. param[in] there is no input parameter and the function does not return anything 


.SH "Author"
.PP 
Generated automatically by Doxygen for Smart Automated Banking Machine from the source code\&.
